@startuml

!define SPRITESURL https://raw.githubusercontent.com/mraziz2007/plantuml/master/sprites

!includeurl SPRITESURL/router.puml
!includeurl SPRITESURL/layer3switch.puml
!includeurl SPRITESURL/cloud.puml
!includeurl SPRITESURL/db.puml
!includeurl SPRITESURL/camera.puml
!includeurl SPRITESURL/circuitbreaker.puml
!includeurl SPRITESURL/circuitbreaker1.puml
!includeurl SPRITESURL/dbserver.puml
!includeurl SPRITESURL/firewall.puml
!includeurl SPRITESURL/LAN1.puml
!includeurl SPRITESURL/loadbalancer.puml
!includeurl SPRITESURL/meraki.puml
!includeurl SPRITESURL/server.puml
!includeurl SPRITESURL/vpn.puml
!includeurl SPRITESURL/webserver.puml
!includeurl SPRITESURL/wifi.puml
!includeurl SPRITESURL/pa.puml
!includeurl SPRITESURL/lb.puml
!includeurl SPRITESURL/f5.puml
!includeurl SPRITESURL/linuxserver.puml
!includeurl SPRITESURL/phone.puml
!includeurl SPRITESURL/realphone.puml
!includeurl SPRITESURL/ap.puml
!includeurl SPRITESURL/k3s.puml
!includeurl SPRITESURL/pod.puml
!includeurl SPRITESURL/docker.puml
!includeurl SPRITESURL/nginx.puml
!includeurl SPRITESURL/nexusrepo.puml
!includeurl SPRITESURL/rabbitmq.puml
!includeurl SPRITESURL/sonarqube.puml
!includeurl SPRITESURL/pc.puml
!includeurl SPRITESURL/switch.puml
!includeurl SPRITESURL/portgroup.puml

'Theme parameters
scale 1



@enduml
