sprite $lb [75x75/16] {
01010010037BBDEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDCA84000010010
00100003BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC30001001
0000009FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB100000
01001DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF30010
0001EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3001
000DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC8AFFFFFFFFFFFFFFFFFFFFFFFFE100
009FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA30006FFFFFFFFFFFFFFFFFFFFFFFFB00
03FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA2000000CFFFFFFFFFFFFFFFFFFFFFFFF40
0AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF82001011004FFFFFFFFFFFFFFFFFFFFFFFFC0
2FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7000110100100CFFFFFFFFFFFFFFFFFFFFFFFF4
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9000010010100106FFFFFFFFFFFFFFFFFFFFFFFF8
AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF50000000000000000CFFFFFFFFFFFFFFFFFFFFFFFB
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD001001001010010105FFFFFFFFFFFFFFFFFFFFFFFE
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD010010010101101000DFFFFFFFFFFFFFFFFFFFFFFE
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF500004D600100101008FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF736CFE101000010001FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF90010076000009FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF301010DD010004FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD000102FF401102FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8011007FFB00005FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF300000CFFF8004FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC000004FFFFFEDFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF600110AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF101001EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA010005FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD876201000AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA30000010100DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF40001011010002EFFFFFFFFFFFFF402BFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFD0001101001010000CFFFFFFFFFFF40000AFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFD000100000000010000CFFFFFFFFFD000100AFFFFFFFFFFFF
FFFFFFFFE84348FFFFFFFFFFFF201010048BB840010101FFFFFFFFFE00110009FFFFFFFFFFF
FFFFFFF800000008FFFFFFFFF7000101CFFFFFFD2010106FFFFFFFFF800010009FFFFFFFFFF
FFFFFF40000000004FFFFFFFD000103FFFFFFFFFF401000CFFFFFFFFF600010009FFFFFFFFF
FFFFF6000000000007FFFFFF701101EFFFFFFFFFFF101106FFFFFFFFFF701011009FFFFFFFF
FFFFD0000000000000EFFFFF300007FFFFFFFFFFFF900002DCCCBCCCCDD20000000AFFFFFFF
FFFF7000000000000023333301000CFFFFFFFFFFFFE1001000000000001101001000CFFFFFF
FFFF4000000000000000000010101FFFFFFFFFFFFFF20101001010010100101101001EFFFFF
FFFF3000000000000000100101004FFFFFFFFFFFFFF50010100101001001010010100AFFFFF
FFFF4000000000000000000010002FFFFFFFFFFFFFF30001000000000000100001000DFFFFF
FFFF7000000000000000000000100DFFFFFFFFFFFFE0000000000000000010100100AFFFFFF
FFFFC0000000000000BEDCDD100008FFFFFFFFFFFF900001BBABAAAABAD501001009FFFFFFF
FFFFF5000000000006FFFFFF601102FFFFFFFFFFFF201105FFFFFFFFFFB00011007FFFFFFFF
FFFFFF20000000003FFFFFFFC000105FFFFFFFFFF501000BFFFFFFFFFA00010008FFFFFFFFF
FFFFFFF500000006FFFFFFFFF6000002DFFFFFFE3000005FFFFFFFFFB00000008FFFFFFFFFF
FFFFFFFFD52226DFFFFFFFFFFE00010005BDDB50001000DFFFFFFFFF10001008FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFB0001100000000110009FFFFFFFFFD0011008FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFA00001010010100009FFFFFFFFFFF200009FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFD20001010010000CFFFFFFFFFFFFE200AFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF810000001000CFFFFFFFFFFFFFFFCEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB654100100BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9010105FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE101001EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF500000AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB000104FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF200010CFFF9106FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8011008FFC00006FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC000103FF501101FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF400100ED000004FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF70101087010008FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA47EFE001001010100EFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF700006E500100101007FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD000000120000000000DFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD000010000101001005FFFFFFFFFFFFFFFFFFFFFFFF
BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF40110101101001000BFFFFFFFFFFFFFFFFFFFFFFFD
7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE6000010010110105FFFFFFFFFFFFFFFFFFFFFFFF9
2FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD5000010100100BFFFFFFFFFFFFFFFFFFFFFFFF4
0BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD70000100104FFFFFFFFFFFFFFFFFFFFFFFFC0
04FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF70001100BFFFFFFFFFFFFFFFFFFFFFFFF50
00BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF820005FFFFFFFFFFFFFFFFFFFFFFFFC01
001EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA68FFFFFFFFFFFFFFFFFFFFFFFFF200
0002FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4001
00102FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF40001
010101CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC200010
00100005DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE50001101
01010000049CDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEECA5000010010
}

