sprite $nexusrepo [75x75/16] {
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDBBBBBBBBBBBBBCCBBBBBBBBCCBBBBCCBB0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDBBBBBBBBBBBBBCCBBBBBBBBCCBBBBCCBB0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDBBBBBBBBBBBBBCCBBBBBBBBCCBBBBCCBB0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDBBBBBBBBBBBBBCCBBBBBBBBCCBBBBCCBB0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDBBBBBBBBBBBBBCCBBBBBBBBCCBBBBCCBB0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDBBBBBBBBBBBBBCCBBBBBBBBCCBBBBCCBB0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDBBBBBBBBBBBBBCCBBBBBBBBCCBBBBCCBB0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDBBBBBBBBBBBBBBBBBBBBBBBCCBBBBCCBB0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDBBBBBBBBBBBBBBBBBBBBBBBCCBBBBCCBB0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDCCBBBBBBBBBBBBBBBBBBBBBCCBBBBCCBB0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDCBBBBBBBBBBBBBBBBBBBBBCCBBBBCCBB0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDCCBBBBBBBBBBBBBBBBBBBBBCCBBBBCCBB0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDCCBBBBBBBBBBBBBBBBBBBBBBCBBBBCCBB0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDCCBBBBBBBBBBBBBBBBBBBBBBBBBBBCCBB0000
0000DEEEEEEEEEEEEEEEEEEEEEEEDDEEEEEEEDCCBBBBBBBBBBBBBBBBBBBBBBBBBBBCCBB0000
0000DEEEEEEEEEEEEEEEEEEEEEEEDDEEEEEEEDCCBBBBBBBBBBBBBBBBBBBBBBBBBBBCCBB0000
0000DEEEEEEEEEEEEEEEEEEEEEEEDDEEEEEEEDCCBBBBBBBBBCBBBBBBBBBBBBBBBBBBCBB0000
0000DEEEEEEEEEEEEEEEEEDEEEEEDDEEEEEEEDCCBBBBBBBBBCBBBBBBBBBBBBBBBBBBBBB0000
0000EEEEEEEEEEEEEEEEEEDEEEEEDDEEEEEEDBCCBBBBBBBBBCBBBBBBBBBBBBBBBBBBBBD0000
0000EEEEEEEEEEEEEEEEEEDEEEEEDDEEEDCCBBBBBBBBBBBBBCBBBBCCBBBBBBBBBBBBCDE0000
0000EEEEEEEEEEEEEEEEEEDEEEEEDDEECBBBBBBBBBBBBBBBBCBBBBCCBBBBBBBBBBCDEEE0000
0000EEEEEEEEEEEEEEEDEEDEEEEEDEECBCBBBBBBBBBBBBBBBCBBBBCCBBBBBBBBBCEEEDE0000
0000EEEEEEEEEEEEEEEDEEDEEEEEEDBBCCBBBBBBBBBBBBBBBCBBBBCCBBBBCBBCEEEEEEE0000
0000EEEEEEEEEDEEEEEDEEDEEEEECBBCCCBBBBBBBBBBBBBBBBBBBBCCBBBBBBDEEEEEEEE0000
0000EEEEEEEEEDDDDEEEEEDEEEECBCCCCCBBBBBBBBBBBBBBBBBBBBCBABCCDDEEEEEEEEE0000
0000EEEEEEEEEDDDDDEDEEDEFDCBCCCCCCBBBBBBBBBBBBBBBBBBBBBCCDEEEDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDDEEBBCCCCCCCBBBBBBBBBBBBBBBBBBBCDEEEDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDEDBBCCCCCCCCBBBBBBBBBBBBBBBBBBBCEDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCEDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCEDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCEDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCEDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCEDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCEDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDEDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBBBCEDDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBBBDEDDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBBCEDDDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBBDEDDDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBCEDDDDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBCEDDDDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBCEDDDDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBCEDDDDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBCEDDDDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBCEDDDDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBCEDDDDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBCEDDDDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDDDECBBBBBBBBBBBBBBBBBBBBBBBBBBDEEDDDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDDDEEEECBCCCCCCCBBBBBBBBBBBBBBBBDEEEEDDDDDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDDDEEEEEEDCBCCCCCCCBBBBBBBBBBBBBBDEEEEEEEEEDDDDDEEEEEEEE0000
0000EEEEEEEEEDDDEDEEEDEEEEDBBCCCCCBBBBBBBBBBBBBDEEEEEEEEEEEDDDDEEEEEEEE0000
0000EEEEEEEEEDEEEDEEEDEEDEEDCBCCCCBBBBBBBBBBBCEEEEEEEEEEEEEEEEEEEEEEEEE0000
0000EEEEEEEEEEEEEDEEEDEEDEEEECBCCCBBBBBBBBBBCEEEEEEEEEEEEEEEEEEEEEEEEEE0000
0000EEEEEEEEEEEEEDEEEDEEDEEEEECBCCBBBBBBBBBDEEEEEEEEEEEEEEEEEEEEEEEEEEE0000
0000EEEEEEEEEEEEEEEEEDEEDEEEEEEDBBBBBBBBBCDEEEEEEEEEEEEDEEEEEEEEEEEEEEE0000
0000EEEEEEEEEEEEEEEEEDEEDEEEEEDEDCBBBBBBCEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE0000
0000DEEEEEEEEEEEEEEEEEEEDEEEEEDEEEDCCBBDEEDEEEEEEEEEEEEEEEEEEEEEEEEEEEE0000
0000DEEEEEEEEEEEEEEEEEEEDEEEEEDEEEEEEDEEEEDEEEEEEEEEEEEEEEEEEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEDEEEEEEEEEEEDEEEEEEEEEEEEEEEEEEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEDEEEEEEDEEEEDEEEEEEEEEEEEEEEEEEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEDEEEEEEDEEEEDEEEEEEEEEEEEEEEEEEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEDEEEEEEDEEEEDEEEEEEEEEEEEEEEEEEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDEDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDEEEEEEEEEEEEEEEEEEEEEDEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDEEEEEEEEEEEEEEEEEEEEEDEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDEEEEDEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDEEEEDEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDEDDEEEEDEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDEDDEEEEDEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDEDDEEEEDEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDEDDEEEEDEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEDEEEEEEEEEEEEEEEEEEDEDDEEEEDEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEDEEEEEEEEEEEEEEEEEEDEDDEEEEDEEEEEEEEEED0000
0000DEEEEEEEEEEEEEEEEEEEEEEEEEEEDEEEEEEEEEEEEEEEEEEDEDDEEEEDEEEEEEEEEED0000
}

