sprite $pa [75x77/16] {
xDc7hTum48H1_igw_ljrHlBBsfFZJ0qVi3Xot0q00000082wRZnZEuu3vh35lCIfle1rND6PubPVm9HjT5xYEAiAZd5HMufhNO1zZbeSppdg1-ppHRSUBTZd
npRVrU9upbxFmZvFPztLudZ6uwpdO9yVIzLDBOuF7ItOvmfQx7p9mJxVrE9upbmlmZu7BJQ-v62VRsfnN7Z9mJxVqEAuylsCVSvRp8yMx7FUOlwIWtsEMkm_
Mh3FUOlvqO9zpblClv-nptcB-VSpzZbliVzemJxdBUOlETZdlCNy-ndxdBUOl-HWd_CMyvSSx7FUOlxzZ7tEM-m_Mh3FUOlvImxsEMynFrgmptcB-KiEzZbl
CVz-nZxtjpZYxsViSzvY_fA3VSvRp5zoiCzvYy7HWdrkRp5_oS4-voq6ty_OvzOMWwC5-zpSuWYE5knpNul1zpFskRN5LuyMU0JxdBSuLm3xtDVYNZdiSzxY
uwmSzZblSQi0zhclnRDosEUynRa2sEU-5e_AOP_p5gVw0PPWd_CMjmfWd_jQF2k7VSvRN2k0VKvRV7gqm3c2VOvRdEi7s8DzpblSwmUOWtsEMtoSbSC-voq-
rkCxM89z3bjy2l9zpbk4V9_p5Y7Ovp-oHUnpVulOvt-eHUnptYBs-Pzf4VkSjmXB_Hajmlh_jOWMf_DdCFsM5kU2btlH8be4BQ95BTPdTkca000G281G_zOs
cAVNGWPmCU4Yk8YBu6B1HN0H5y75WelW8Yw2YmKNmKLS11SBBeABk0Wk5bm45t4HN2ou22xY8hXOS15Sn4LmiU0Yk8YBu6B1HN0H5y75WelW8Yw2YmKNmKLS
11SBBeABk0Wk5bm45t4HN2ou22xY8hXOS15Sn4LmiU0Yk8YBu6B1HN0H5y75WelW8Yw2YmKNmKLS11SBBeABk0Wk5bm45t4HN3m35rdidObowpeIGqsA6rh_
_xrlysoPn25z3VTjCK1DBREfKjPvic2Wcy0O0u3zHeb52QEt-Y-r3ZC3p5zYKI2sMakf_rKRzezWZXABqcYrrFzNWpE9Ob72LoJMMkemJub5gTTIwfSg7UOb
iIYXrs_KpKLYKOAXbVf0hb_JOb4erkzL6ZpCj5YKq4gTg7cGA1QbLcSgTRYmA1RbeEj47lP5B4gZhgZ1F2GMzGqz5-oz4ejIBtL9mzugiIYXBggRdyIY7eln
VzKHYtfRhEL9yo8M9V1Dz5tD72GMzHLDPb4iIh1drLPPBDtS9HRbelrP58lIM6Tns9B4eWJ367ZQkfIwAjXKOb72g2NV_b4kVRp5kjGfvs9HGist_rKgm-u2
qqPFBYOM9PHq-wG2Mn9uDbeiQZWWtRvIxcOWssZO8ub5aMZzuUULEir6psiwOb5gwVPOpSr6YqMfthvJ6ePPHjDhUTswY4MftBvNnebfIQUyaaQBHGaJ59U_
fUlhBHsnA1ZRRQe4WesUjBh5eZJIRQxsTXij5YNasuBoT33wDHij5YLOlIrfpAmB9G4KY_g6dgjFtZdVQrt4edxEMRq_Q4xMHIpgiNWx7AoBM5JWuiTYcR0e
5cMYvygKyc9vOAF5eZHkdETYBw_DwOj5gTrMLRpcKV6nHev_PEVzFyFEBEf0HeQFHcMn-054z5QEz9VoKJjECpFiogAKRglwbY5GRJJko8sIFytURFfSb62u
BGkadtImz5JyicUU3foxiYZrswhI98scMfU74m-fxSgYL6-hofmqkhIbR-YQ9g-jsx4e5OADvXTfSKpAQnkoAENRgfh1eKWBCzZ8ax_aHxEerEKs76pq7VS-
yVPfRCYYD58y6pt_cuwDMTIWormPf5AtVIiiFQhxTYnAPsKbW3phShmMZU_FecnqTIdIOkr9dSOFPb7MfP7MEWtA2spRZKK9f3HwhBC8Cxp-e2u_bqML5zEW
RQGrl1v9PlnO5bLUpBIDj9G6MzgDHQcIIjsDLEeUjn_AeWIMZMQLkgjOb8qEKgJDFvL52JTE6ZrABGmMHnABKyb6WsMZNxDIyj6oqGSh0QILARTYKJgBTnfT
M2pMpLYK3lS4i3iaac9HHLgITL4tmaKgqWxEJ6B6ZsLHywXms8vylc2bnA8IGAgDVh7OAnPLfBLMbbbahVOvnU96Wi7THjTEIoJ5ej9eWdLXb2d5uZO2YFT-
r6M1jTf7B6uZcDdPMKNQwfv6YyLNfJGQ3cdqrYogI5iuywYbWxJQPpCMfMZpgEd5H58igaZha4QBnOq5Nf5s-5iNxCMYnB7H8CoZ4bRxN9f5YRVMoJq158iw
sEMD2U1JYUGf5dMmonjP78HYhrYyfaQAPQFxyj-JnQAAj44Im0DYSIE1T-zxa2AjM5IHrdyskfvYSIzTk4Wh5Xz8QvqA8ut6KsLAYCMDD5Aa8YqbaToVHIM0
sAf8AnPLf2tKjKuGY_ke-1TfgMLAiRYBUFEewxFHdPT8GYn-8Htimjb8YzkoeEUYDjAkRaVsdqSLYohIclKL5ikaICjOxICMjTR9VoEjM5IHDhYDtfz5pQFs
O6dq48jx2PIDjB1HtBSZYqNPQ6O2wByT6M8ngfhhMYUkZHQBIW2lMwI5lgDLf8qoZmgnwA7J03lFqEUZbbg-On7kraKiyeNUQZcEKcf7w29j-Nr5MWo8nNUl
E4Ox_WUfT7JxMuXQf6KdadC1hUISKigvT8Z5jmXssgYVxrEtDPsq8cs9QwD7-t3xqz7jjBy5iKZLAEbBqmldjKx-1xkyy04TGoporTB3zHvdoBLEnVTW5zHq
-qAfmQ3lQAz5ssc4FDYbk1PfUxuzK869HQ9ml9gHZTksywYOl84KiKWI5dR35JFu5MdzrphXjHUGAXPfGdezcN2tqQMv998mdBC89tMnwBTw9C7WD8zQmXLf
vsbYXbZqApMqgntiGhJHvJPL4uiKLKOs0U-DjCMfI8kbjuyi5Xsdzs3cyHFAu5YNarQaFViIrLqi-bMzMlWqcc-biFxvb5CilYGy0L49c022D8-AnoIkGfrD
BBeDxsMN8gqzLQG5v-zvpE9wd9GW5bzLvvoPPlxpgCCCxq-Zwx834ejkGogPVB0BVwqJFv744qntiUYsOJjx7UnI8XLf-qqinfjfpgmYBLYhT4X5sfEJ9ed5
A5kDwtNdKKcpX4Ci-gvZuiyYy-THGKWa9w_1yj4yyLFap9b57dLPh2BjOBrsYiMvMFTiquDTMEcDM7HSn-II01O2Y-2jzgctLLMn66KT4yS2hRDO6lXMYlyA
8nRzrp5L_o8jF6OI2QyUOf6_ZichI5jyIzsTzGeZ5ltEDJrPX_fusEZaRwF5ubGEAJB90X5jT4_B3B5UEyNYY-hkDZfnDjAMHfj79Rt2Y4Kt6rrmeODTJa82
I7hr48jy6rrTaiHMLzLPbenxC8DOd8k_HPXlM_4x3dRff5SFiUXeercsrS56duH4afK0YaL-0ZYy3tRndqVb9m5YqVzSq_RKlGVXTR7IIfaS5ji-BEBIvvgU
pWUx55wHjh1UORPW4HkaqRIDjFuscbM4s-IvYDsBjFnvr18j0OJU5rz4EdaNQMykHLf4ATBkpwAAj8KtZqfAeyyjM1mmXZ3mrY8jx85mvIBjuV3Q6Pj5tF-5
NdFwM_beuzU_be5MZljr9lVe7IqKq9uVXc07ku1JX8l_N4JxU9tS9WSeBLxdQ3WTvb5TRBH_aPR_sXcVHTJFdrTkzhH6_U8WfhOAj4C26Dv6W_FQULaMqTAZ
NXPWwq9DituNwvvvsDPHViiyAWWs-geidkDuU85XJsZaIK4qNf4MBWUxkAVHzQeijZJvSF2w2ywmkMZhcFoBj2I6YiChJ5WMCVcarY32_1C_5gvHWnLfMTQ5
KCea906XMSJIFxILv86hdutsFzYbnofbfckUJLcMKdQ7wx3k6Q8LQMtaPOP8oMQnW2molXQBJKMu3bWj53oJHjFcKJaC7SQvJhyOY-jzus5JzMM0ACbTTh6j
tPt5TbAkat4n5jU_FIffmhxoqkXW1xjKep2KmBbEjGkoMDRkFCbq74v5sk8_ZyfXg1WOZReqBiXY9xnLOVqw2RHvL9TPvBgi0Oed6vo8j9unMQJSj4wAaRjF
0kY-rgaCOqpV54wDAGFNOx4J7XyWN8UT8eTAezSPIg1KZLCtknwBXV1Q1OCT71Pxj8sqTLMDOkqwPvD1DJD4PD7ZfzEHE2pMwnxi0eAtAvp0_h29GhBOA7OJ
PtMn7Fv5MeQDNdzK7uGLBvCkIs0M_LTwjTEZI9lzRRJDT10OMiacCYpiSv5kD-ElOuB_mIxZvJ0W3mCXzZzWrsJnjYnuh6FgoTr66tSUTNAyovGXl0fZWGLc
qU6UqL9a_-lmvb7dgYks1Q_0c9gT2CoYH_avs3ecodNmZ7LfwwD0yny4vutJho-KoZ0B_LoCbVxkMQIjYomzdczR5UwmzUCB4liTrS0iSkvPk7LCf28-rKRF
DSgNJxDdXTDwIHzUDYP_GdGMaNcsrVzSKp3MEk7Rwx1PX9cD3mobN66_ABII_xsQOy3i2YnIxjcbrZ5v5sdBKq2XroF_hQEqyUfsGS3k0YxDOWzcMvjx0dY0
Ux3Bkc20dUQZ-2oUh7jMVyUvfd0eqX9izDo8u9K78Zxww-WiXhA_l28j8XLfk_sg03qNcVS-MfAOVOkqfTPX0OGhivY27UfpyxvESjYEF9MUYymKsR-CpIhI
EgnrcaWiCalK9-qyKlVh55_h8XP99Mgo1Of_7Rvr4OkCUtPoR7HtIHAzRNGfmrwIMCHlIf5X3tJP8cs1BKainagH7sjGYhqW99BEDbei4kvPn2GHlBdMmfa1
d4iizaWfCbX98gnUpaQBnUfVeZxzvb7ZssYnoBzdhEkmx3ZlO9T2BjAAHSezm_lNAFclTG9v7dKkiSYtqVuMo3-HT4W0nIBZdl6JnEPUfZoyhOjOT2XH-rwd
qEPQtKlTOZ5-aPR_z_WVx3ANM2JSis3hc4xETSO9rtbK4uiEwvZ2hEJ1IKWamreNiPXP37bSvwJDepgmA1Qf6sdF6EkO-6bIB_5ij5WSBhQrkb-dSWuPyYil
wZlwCBvjZL-ajHRlAre-kflFEYPtAzKfB9OEyv5-NppCuXTf-LRAMhZHQEKkm_WRQUCdacOzMkYYRaGrWyiwfc3NCVZzq2qMhQpUCD3jR_ovLhDQ8kL_cdV9
C6FRwFY9v5sjrE9geZKVFRSR8DbMLefip4D27ckuVKEBnRa7JdTyM2aooOw3QiVdltQNHmQwa0PTnE9yUZFVwTdsO9UPXjTFYs8HarjtJ50CcI8J4idrI9g1
ebYSivGgJeDDHBZtiOgqwwUa5kwxebZ4sTF3Xo9iecWfCfWs-WvZSR4jOl4kbCyq7ii7A8LQoGF2NEj7ZLRylf_5ejduI6EgmrRbdo9dPf5sBdJFXw9OD4El
EVsjV4mEK29Obr2hVUOQxTEBOdiNYM8HTjVa0AKO1TZZP5gfkM0sMglbBzLIIgsj3nX1Of4i_mIm6ZX_psdhD6BqtlvIxyC1HB4uEK29aVu6FY1cBlmjuqii
heD7iB_q51cCH3AMnEASK9Rb68P81xjas0RI-o9X7LF4SrRZIonkMQGjjeF48l-0c1nWhZMyn6AmSqs7mncPaIKM2ROr-bnhV8b5ZnIv-S-rsbuIYurrpgf_
acWRI2nkKQIj1jj1Of5VfFMVHuNj9B58iAqCEouRBHRXKAJrEjWbliGYwTv7AzB2jf9Oh5iU41DVOZ5-Ydpid02AHPPjPTbncWNQIc8H_aLQNfAubSHYJ_u7
kwX8AnO3hsDIaLOidiN_N5EU1O9j8B4OR1sJRBHO1A-CxN-momuIY_m2BEcSLVpS150ikXHWLQITIopsVGvsYI-no4f_JuwDhcRW56dtabWyWjdedve0YaKW
q3ecR5-a5Oiis-fYn_UnqM8nVf4MAjAAnJWfCdXphV4b5la98Eo1m2paxfm0YaMNvEvmADBkow9OfDbMy0gvFwf8AnRvAJ8uTXox5sd5OgmKMKLQiHX_7HC8
YUHr9HO9jfMP9ABid4QBnNWfikPHnMByTKpO-c0NiSXAVuDV9xx48iksXhlENXABzSBpg7j9B9OOSwGws4Kiuj16sgj9B6RJmIxlb5YqW_ALUFOeAtdsbzuN
4mZsL_Ee1Cb7Lv-vrXyyZoeM-_9Z4UzDerMaLUwI6DalQwvrPDbeTIFcBsVnDjB2jf9ORAi0aHZwZg1phmHGBFABEgaRZ6P_eODTVbcQZswdrqeUmdgedQNT
JiscolxpgBknA1RdvZLr-bmhD8_w2zBvBhcpvrgX8grO_1KO2qw3oqeUfT5Y4MOunp5xAF8Ai2GR3TjHEW_GJglfCuaDDfCETX6BVA5-i32fTFzpLbMa5Olt
PoDwAqTEAUVI1kYPzfn5g4Wh5lyhRB2InqbYqGT719XhLNbHB4vGP1LfvongVObOn1iFY5bWKPiNnI9-zqeUw_gA5ejkAtc6CNnqmWbxHM9HB6PEnQAU9ed5
zwR8PV4gabXyzpgczkkrCx4e5a4gqgv_ILUXA1O91xiGVgayJ1AB3kkOHj9vb6BHvPpLLtsGK1IBZkkO3g4e5XqEvQYlXZZ59B58AjBEXSSmfYO7BHOTjXhF
Fu02ayGYoReCMrFBNv3OJHABj28jR57e7sbCLLcBMEIUixekZ7gakuuwO99OPARHzTag9SO0J1ABdaNQUQaNPf9OT3ZOHHABpaLQc2GM0_oaKuAmA1RrNEmM
Gc9HB2QB8R4e5gj9Ol6j6beaAnQ325aB4yLY41Lj7H6BGTHaeiLY4279k8Z50D8SgLYyreCncoGMGxmnvd6Q91OzX3AhSyCaiUWY7BDAX6WKYmu2pCRnpHof
91OzXVhj72diYXABFLs4nO-KzVp5tplimXABDLtqPpgqptEaLvPOFDA5Vp8UzSWvfPJpvUT8nIBovUCBZB41Xc9nf2j7QTXdWbGijiIFTVrf160NbrWiwTeL
0-Yn-6Sxzx7inX44KRIw1-DD_V_VQaFFb87wlOmAnhqotDAS1MgGd08M7VjeaqN2ujwYWaN2ujAYW4N2elYek9aj4XRr0-vstLwBX4LzjKnFUYqI5lKMOidq
MYGiwYt4bcQBX4NzKV5CiqN2elweUAVN8c5HRo7cJAz5mg9-mBscro9XKJ_WRaVwBH8MzzxYv_gTPek4HRs5MDDkaR2ejn27tI9XSMuXQcwBXCMfXUosMYGi
xZr2PxsZ2OjhYxzhDreaBCujAbWaB4uj2bWaB8ejn6MtI5ZKMuZRRP6mgBSGTek4HRs5i5iaBEejXDSYOL5l8LvF-YqI5lLircgHiAWVS1_fjaXOrE-5IBj5
mg9-BuJT8c5HlnV2Qv6mg3ygxcctI5ZKxuMmMoGiwlT2s2qI5lLx8TmM2Olw0RVT8c5HRo7i5WcBUWjXjqXOr5i8kqN2elwewBP8MDHR2Az5mg9-mDslj5ia
BEejXDqYOL5l8TmM2Ojw2s6tI5ZKMmYxHSAYtaBOBH8MzHR2Qv6mg1zmRsctI5ZKMmYxHSAYtaBOBH8MzHR2Rv6mkAejXDiYOL5l8UmM2Ojw2-6tI5YKMmYl
HSAYRiciO96mk6S5YuJ5TcK5YuJ5wSuA5WcBSsO5YuJ5BIjO92os8ojO92psEojO92pEJrQmI5XSCojO92mUMS4YOR5VwR3OvbyZwc8ByS4MtuzeoQnWaMZF
6XQ9yi-tI5WamY9XyPWYfkt_M2Jg7sZnUNrTGRvlaMZwE8jR_px9ZNSZUerQb6rH8yBYArJj_UA7Mhd6VpdycZxTOl-eZwRhm9LLi85bLDbUOvZwPrkSYbZ4
8XRN6XQnYCLsrR28HImUTmcBMCJYdXKiOX6BxSmA5h68nNwdto8MiVXCukMDVejOnEBTnHjv_1QnYCLJlNBURn6BMDp50MsnY4KiQYRVEpFz5h68nLcyCizl
4OjOVCJwOVTRn28MxnuLB68HYsUB2XQnYCKzee95B69n3TtfjOX5B2uHkiTf4OjOV5uHkZbD5h68HNr0jwy_FaQBMCJY9Rw1Nh_lSrmMiOZ5GzxEzxvkPwRF
8XQnk8a9z_Ti5h68nKLCkFqMiOZ5voKct7QBMCIYdd2xBM8HY_g0jbl48XRr0MstY4KiwWFQRX6BMDG7jDqY5h6e3sYxHInYKH_GRejOnA8-eEqMiOX5VK3R
BM8HY_g0jbl48XRr0MstY4KiwWFQRX6BMDG7jDiY5h6e3sY_HInYKH_GVejOnEAc_lQpto8MiRZ4RwNV8XQn-BoYWaKiOl7kKS4Y5h5ujQXW4OjOF28gMCGY
5hSeOH6BM5oYWaKiOl5vHGMBMCJYtQE0HInYKHpGazqY5h6elu5UxHQnY4KzuRPRn28MzOJRRX6BMDGJRhj5B69HJxZT5h68HJtXjbl48XRrXDjl4OjOb0Uq
to8MiJY90tfSmlAsHInYiOa3UbJ2CuMgdU_t8-hpyzgFqr9yRpu_kUCuBKq_s3dVhyNVDcUEMhnw34Uqvh358yOZsdFOuXh34RKpXotECHnHltFKuZt5S4JJ
awCMhnR34StZJ_Vs68zepM6BQun7jEUenUSLmn6rCqSjtZs68-ftZbeyMun6rBRnPS8M_w5s6Z9yHUpB_nMnlnRVckxCOOjB_9Tw5eZfJ8tqVd7OuZC55Yk4
nQi75Yk4nIC2YnN2uXfOB14Mvy1YXR1uJu752c7nQe752c5nZy1YXR2u1XOhXCNd5LYi41Rl7bYi41QF5bYi41Qt22nM28jpOB52M7ocm6A5i7Yrm6A5i7X4
OB52M5m3YnN2uZC75Yk4nNiAB5O8YsSBB5O8Yti45Yk4nIMmM20igh28HInY4OjOh1yMiOX5B68HYrZ48XQnY4KiOX6BMCJYqx5O8YpUKs2nGbWyMs2nGbZS
8x1O8ImkWSKAOV5v1HOhXCMh1nOhXCMZ1HOhXCKj0eiLmk8SMAmG5fyfi5WXB5uji5WXB1uHMAmG5jV0OeMm-Co1nGfXyUw1nGfXyMo1nGfXSGyH5lrXSGaH
5hrXKSzoiEWFYtgMWqL_MDIp72pwm-8M8YpQm-8qXwksLYo-Dwr_I3s-rTVYjH0LZeY8Y8Y8Y8Y8Y8Y8YFu2
}

